#cloud-config

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - git

runcmd:
  - [ sh, -c, "systemctl enable docker && systemctl start docker" ]
  - [ sh, -c, "git clone https://github.com/nethu9/home-assignment.git /opt/home-assignment" ]
  - [ sh, -c, "echo 'WEATHER_API_KEY=${weather_api_key}' > /opt/home-assignment/.env" ]
  - [ sh, -c, "cd /opt/home-assignment && docker-compose --env-file .env up -d" ]