#cloud-config

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - git

write_files:
  - path: /opt/home-assignment/.env
    content: |
      WEATHER_API_KEY=${weather_api_key}

runcmd:
  - [ sh, -c, "systemctl enable docker && systemctl start docker" ]
  - git clone https://github.com/nethu9/home-assignment.git /opt/home-assignment
  - cp /opt/home-assignment/.env /opt/home-assignment/.env
  - cd /opt/home-assignment && docker-compose --env-file .env up -d