global:
  scrape_interval: "20s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
scrape_configs:
  - job_name: "temperature-exporter"
    static_configs:
      - targets: ['temperature-exporter:8000']
    metrics_path: /metrics
    scheme: http