name: Deploy Infra + Monitoring
on:
  workflow_dispatch:
  #push:
    #branches:
     # - main
jobs:
  provision-azure-infra:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SetUp Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
      - name: Terraform Provisioning
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform plan -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
          terraform apply --auto-approve -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"