name: Deploy Infra + Monitoring

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  environment-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SetUp Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

  sonarcloud-scan:
    runs-on: ubuntu-latest
    needs: environment-setup
    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=app

  terraform-provision:
    runs-on: ubuntu-latest
    needs: sonarcloud-scan
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_weather_api_key: ${{ secrets.WEATHER_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SetUp Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Provisioning
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply --auto-approve